name: imotion_designs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.3.4
  sqflite_common_ffi_web: ^0.4.5+3
  path: ^1.9.0
  path_provider: ^2.1.5
  spider_chart_extended: ^0.0.2
  flutter_radar_chart: ^0.2.1
  fl_chart: ^0.69.0
  wakelock_plus: ^1.2.8
  flutter_dotenv: ^5.2.1
  restart_app: ^1.3.2
  connectivity_plus: ^6.1.0
  provider: ^6.1.2
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0
  video_player: ^2.9.2
  google_fonts: ^6.2.1
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  flutter_screenutil: ^5.9.3
  audioplayers: ^6.1.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icon.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icono_app.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icon in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/fondo.jpg
    - assets/images/logo.png
    - assets/images/recuadro.png
    - assets/images/back.png
    - assets/images/tick.png
    - assets/images/papelera.png
    - assets/images/ajustes.png
    - assets/images/bio.png
    - assets/images/cliente.png
    - assets/images/panel.png
    - assets/images/programas.png
    - assets/images/tutoriales.png
    - assets/images/avatar_back.png
    - assets/images/avatar_front.png
    - assets/images/Abdominales.png
    - assets/images/Isquios.png
    - assets/images/Pectorales.png
    - assets/images/Cuádriceps.png
    - assets/images/Dorsales.png
    - assets/images/Gemelos.png
    - assets/images/Glúteos.png
    - assets/images/Lumbares.png
    - assets/images/Bíceps.png
    - assets/images/Trapecios.png
    - assets/images/ABDOMINAL.png
    - assets/images/BASIC.png
    - assets/images/BODYBUILDING.png
    - assets/images/BODYBUILDING2.png
    - assets/images/CALIBRACION.png
    - assets/images/CAPILLARY.png
    - assets/images/CARDIO.png
    - assets/images/CELULITIS.png
    - assets/images/CONTRACTURAS.png
    - assets/images/DEFINICION.png
    - assets/images/DOLORMECANICO.png
    - assets/images/DOLORNEU.png
    - assets/images/DOLORQUIM.png
    - assets/images/DRENAJE.png
    - assets/images/FITNESS.png
    - assets/images/GLUTEOS.png
    - assets/images/METABOLIC.png
    - assets/images/RELAX.png
    - assets/images/RESISTENCIA.png
    - assets/images/SLIM.png
    - assets/images/programacreado.png
    - assets/images/STRENGTH.png
    - assets/images/STRENGTH1.png
    - assets/images/STRENGTH2.png
    - assets/images/SUELOPELV.png
    - assets/images/WARMUP.png
    - assets/images/CROSSMAX.png
    - assets/images/HIPERTROFIA.png
    - assets/images/RESISTENCIA.png
    - assets/images/RESISTENCIA(ENDURANCE).png
    - assets/images/RESISTENCIA2(ENDURANCE2).png
    - assets/images/TONING.png
    - assets/images/PAUSA.png
    - assets/images/RAMPA.png
    - assets/images/CONTRACCION.png
    - assets/images/pantalon_front.png
    - assets/images/pantalon_post.png
    - assets/images/lumbar_pantalon.png
    - assets/images/biceps_azul_pantalon.png
    - assets/images/isquios_pantalon.png
    - assets/images/gluteos_shape.png
    - assets/images/gluteoinf_pantalon.png
    - assets/images/gemelos_pantalon.png
    - assets/images/cuadriceps_pantalon.png
    - assets/images/abdomen_pantalon.png
    - assets/images/biceps-pantalon.png
    - assets/images/ibodyPro.png
    - assets/images/obtenerBio.png
    - assets/images/leerbio.png
    - assets/images/espana.png
    - assets/images/francia.png
    - assets/images/italia.png
    - assets/images/portugal.png
    - assets/images/reino-unido.png
    - assets/images/mujer.png
    - assets/images/repeat.png
    - assets/images/flderecha.png
    - assets/images/flizquierda.png
    - assets/images/chalecoblanco.png
    - assets/images/pantalonblanco.png
    - assets/images/virtualtrainer.png
    - assets/images/rayoaz.png
    - assets/images/rayoverd.png
    - assets/images/absazul.png
    - assets/images/pecazul.png
    - assets/images/cuazul.png
    - assets/images/gemelosazul.png
    - assets/images/bicepsazul.png
    - assets/images/gluteoazul.png
    - assets/images/dorsalazul.png
    - assets/images/isquioazul.png
    - assets/images/lumbarazul.png
    - assets/images/trapazul.png
    - assets/images/trap_gris.png
    - assets/images/trap_blanco.png
    - assets/images/trap_naranja.png
    - assets/images/lumbar_gris.png
    - assets/images/lumbar_gris_pantalon.png
    - assets/images/lumbar_blanco.png
    - assets/images/lumbar_naranja.png
    - assets/images/lumbar_naranja_pantalon.png
    - assets/images/abs_gris.png
    - assets/images/abs_blanco.png
    - assets/images/abs_naranja.png
    - assets/images/pec_gris.png
    - assets/images/pec_blanco.png
    - assets/images/pec_naranja.png
    - assets/images/biceps_blanco.png
    - assets/images/biceps_gris.png
    - assets/images/biceps_naranja.png
    - assets/images/cua_gris.png
    - assets/images/cua_blanco.png
    - assets/images/cua_naranja.png
    - assets/images/gemelos_gris.png
    - assets/images/gemelos_blanco.png
    - assets/images/gemelos_naranja.png
    - assets/images/dorsal_gris.png
    - assets/images/dorsal_blanco.png
    - assets/images/dorsal_naranja.png
    - assets/images/gluteo_blanco.png
    - assets/images/gluteo_gris.png
    - assets/images/gluteo_naranja.png
    - assets/images/isquio_gris.png
    - assets/images/isquio_blanco.png
    - assets/images/isquio_naranja.png
    - assets/images/lumbar_pantalon_azul.png
    - assets/images/biceps_blanco_pantalon.png
    - assets/images/cua_blanco_pantalon.png
    - assets/images/gemelo_blanco_pantalon.png
    - assets/images/lumbar_blanco_pantalon.png
    - assets/images/isquio_blanco_pantalon.png
    - assets/images/avatar_frontal.png
    - assets/images/avatar_post.png
    - assets/images/pantalon_frontal.png
    - assets/images/pantalon_posterior.png
    - assets/images/RESET.png
    - assets/images/average.png
    - assets/images/mas.png
    - assets/images/menos.png
    - assets/images/play.png
    - assets/images/pause.png
    - assets/images/RELOJ.png
    - assets/images/flecha-arriba.png
    - assets/images/flecha-abajo.png
    - assets/images/capa_pecho_azul.png
    - assets/images/capa_abs_azul.png
    - assets/images/capa_trap_azul.png
    - assets/images/capa_gem_azul.png
    - assets/images/capa_biceps_azul.png
    - assets/images/capa_cua_azul.png
    - assets/images/capa_dorsal_azul.png
    - assets/images/capa_gluteo_azul.png
    - assets/images/capa_lumbar_azul.png
    - assets/images/capa_isquio_azul.png
    - assets/images/capa_isquio_azul_pantalon.png
    - assets/images/capa_lumbar_azul_pantalon.png
    - assets/images/capa_abs_inf_azul_pantalon.png
    - assets/images/capa_abs_sup_azul_pantalon.png
    - assets/images/capa_glut_sup_azul_pantalon.png
    - assets/images/capa_glut_inf_azul_pantalon.png
    - assets/images/capa_biceps_azul_pantalon.png
    - assets/images/capa_cua_azul_pantalon.png
    - assets/images/capa_gem_azul_pantalon.png
    - assets/images/capa_pec_blanco.png
    - assets/images/capa_biceps_blanco.png
    - assets/images/capa_abs_blanco.png
    - assets/images/capa_cua_blanco.png
    - assets/images/capa_gemelo_blanco.png
    - assets/images/capa_trap_blanco.png
    - assets/images/capa_dorsal_blanco.png
    - assets/images/capa_lumbar_blanco.png
    - assets/images/capa_gluteo_blanco.png
    - assets/images/capa_isquio_blanco.png
    - assets/images/capa_isquio_blanco_pantalon.png
    - assets/images/capa_biceps_blanco_pantalon.png
    - assets/images/capa_abs_inf_blanco.png
    - assets/images/capa_abs_sup_blanco.png
    - assets/images/capa_glut_sup_blanco.png
    - assets/images/capa_glut_inf_blanco.png
    - assets/images/capa_cua_blanco_pantalon.png
    - assets/images/capa_gem_blanco_pantalon.png
    - assets/images/capa_lumbar_blanco_pantalon.png
    - assets/images/capa_abs_naranja.png
    - assets/images/capa_pec_naranja.png
    - assets/images/capa_biceps_naranja.png
    - assets/images/capa_cua_naranja.png
    - assets/images/capa_gemelos_naranja.png
    - assets/images/capa_trap_naranja.png
    - assets/images/capa_dorsal_naranja.png
    - assets/images/capa_lumbar_naranja.png
    - assets/images/capa_gluteo_naranja.png
    - assets/images/capa_isquio_naranja.png
    - assets/images/capa_abs_gris.png
    - assets/images/capa_pec_gris.png
    - assets/images/capa_biceps_gris.png
    - assets/images/capa_cua_gris.png
    - assets/images/capa_gemelos_gris.png
    - assets/images/capa_trap_gris.png
    - assets/images/capa_dorsal_gris.png
    - assets/images/capa_lumbar_gris.png
    - assets/images/capa_gluteos_gris.png
    - assets/images/capa_isquio_gris.png
    - assets/images/capa_isquio_naranja_pantalon.png
    - assets/images/capa_biceps_naranja_pantalon.png
    - assets/images/capa_abs_inf_naranja_pantalon.png
    - assets/images/capa_abs_sup_naranja_pantalon.png
    - assets/images/capa_glut_inf_naranja_pantalon.png
    - assets/images/capa_glut_sup_naranja_pantalon.png
    - assets/images/capa_gemelos_naranja_pantalon.png
    - assets/images/capa_lumbar_naranja_pantalon.png
    - assets/images/capa_cua_naranja_pantalon.png
    - assets/images/capa_cua_gris_pantalon.png
    - assets/images/capa_abs_inf_gris_pantalon.png
    - assets/images/capa_abs_sup_gris_pantalon.png
    - assets/images/capa_biceps_gris_pantalon.png
    - assets/images/capa_isquio_gris_pantalon.png
    - assets/images/capa_lumbar_gris_pantalon.png
    - assets/images/capa_gemelos_gris_pantalon.png
    - assets/images/capa_glut_inf_gris_pantalon.png
    - assets/images/capa_glut_sup_gris_pantalon.png
    - assets/images/fullscreen.png
    - assets/images/31.png
    - assets/images/30.png
    - assets/images/29.png
    - assets/images/28.png
    - assets/images/27.png
    - assets/images/26.png
    - assets/images/25.png
    - assets/images/24.png
    - assets/images/23.png
    - assets/images/22.png
    - assets/images/21.png
    - assets/images/20.png
    - assets/images/19.png
    - assets/images/18.png
    - assets/images/17.png
    - assets/images/16.png
    - assets/images/15.png
    - assets/images/14.png
    - assets/images/13.png
    - assets/images/12.png
    - assets/images/11.png
    - assets/images/10.png
    - assets/images/9.png
    - assets/images/8.png
    - assets/images/7.png
    - assets/images/6.png
    - assets/images/5.png
    - assets/images/4.png
    - assets/images/3.png
    - assets/images/2.png
    - assets/images/1.png
    - assets/images/seleccion_cliente.png
    - assets/images/EKCAL.png
    - assets/images/ojo1.png
    - assets/images/ojo2.png
    - assets/images/apagar.png
    - assets/images/back2.png
    - assets/images/icono-vita.png
    - assets/images/cliente_ia.png
    - assets/images/i-icon.png
    - assets/icon/icono_app.png
    - .env
    - assets/traduccionesv25.json
    - assets/videos/tutorial.mp4
    - assets/sounds/beep.mp3

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
