// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9JgT0Kt_-oGS3G6mTaKm35O-6SYJ86c',
    appId: '1:1093761830210:web:8952e244ffbe5cfcb5ccdb',
    messagingSenderId: '1093761830210',
    projectId: 'traducciones-v25',
    authDomain: 'traducciones-v25.firebaseapp.com',
    storageBucket: 'traducciones-v25.firebasestorage.app',
    measurementId: 'G-8EEWF5KLWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMlx0YOt0_8Wvb4tT2Yhn4E4KRMS0metY',
    appId: '1:1093761830210:android:f8dc7e0abcb39a71b5ccdb',
    messagingSenderId: '1093761830210',
    projectId: 'traducciones-v25',
    storageBucket: 'traducciones-v25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1IbbTBaZklY6ZF3kJaYtbVgi9d6g_WI',
    appId: '1:1093761830210:ios:6ba37a4ee2746795b5ccdb',
    messagingSenderId: '1093761830210',
    projectId: 'traducciones-v25',
    storageBucket: 'traducciones-v25.firebasestorage.app',
    iosBundleId: 'com.example.imotionDesigns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf1IbbTBaZklY6ZF3kJaYtbVgi9d6g_WI',
    appId: '1:1093761830210:ios:6ba37a4ee2746795b5ccdb',
    messagingSenderId: '1093761830210',
    projectId: 'traducciones-v25',
    storageBucket: 'traducciones-v25.firebasestorage.app',
    iosBundleId: 'com.example.imotionDesigns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk9JgT0Kt_-oGS3G6mTaKm35O-6SYJ86c',
    appId: '1:1093761830210:web:74a96468712b52c8b5ccdb',
    messagingSenderId: '1093761830210',
    projectId: 'traducciones-v25',
    authDomain: 'traducciones-v25.firebaseapp.com',
    storageBucket: 'traducciones-v25.firebasestorage.app',
    measurementId: 'G-NN3EPJX12E',
  );
}
