// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNH9kTZj1bjOvMkSCPXxWyjbb9dcT6CFQ',
    appId: '1:313073231514:web:b2b0274676aa4d871ea123',
    messagingSenderId: '313073231514',
    projectId: 'traducciones-v25-imotion',
    authDomain: 'traducciones-v25-imotion.firebaseapp.com',
    storageBucket: 'traducciones-v25-imotion.firebasestorage.app',
    measurementId: 'G-SQMGZ7002J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Zh3MoE4eKHVOAtgd10nACwfcVYgKlnU',
    appId: '1:313073231514:android:732e8c39ce30a72b1ea123',
    messagingSenderId: '313073231514',
    projectId: 'traducciones-v25-imotion',
    storageBucket: 'traducciones-v25-imotion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuv5SZqeI2JLx42W5y48BIq_EUmiZQc_Y',
    appId: '1:313073231514:ios:02b152d03cc96b5a1ea123',
    messagingSenderId: '313073231514',
    projectId: 'traducciones-v25-imotion',
    storageBucket: 'traducciones-v25-imotion.firebasestorage.app',
    iosBundleId: 'com.example.imotionDesigns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuv5SZqeI2JLx42W5y48BIq_EUmiZQc_Y',
    appId: '1:313073231514:ios:02b152d03cc96b5a1ea123',
    messagingSenderId: '313073231514',
    projectId: 'traducciones-v25-imotion',
    storageBucket: 'traducciones-v25-imotion.firebasestorage.app',
    iosBundleId: 'com.example.imotionDesigns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNH9kTZj1bjOvMkSCPXxWyjbb9dcT6CFQ',
    appId: '1:313073231514:web:8d0a5a0c66377d231ea123',
    messagingSenderId: '313073231514',
    projectId: 'traducciones-v25-imotion',
    authDomain: 'traducciones-v25-imotion.firebaseapp.com',
    storageBucket: 'traducciones-v25-imotion.firebasestorage.app',
    measurementId: 'G-B1H7FZYT73',
  );

}